### ISSUE TITLE
[Tracking] Needing additional features

### ISSUE THREAD

**Issue by narenchoudhary** [narenchoudhary/CCD#16]
There are some features on here that we are still missing. Some features need discussion on the ideal way to solve the problems. 
## TODO
- [ ] Pagination is needed and it's very very important.
- [ ] AJAX requests for update actions on `company/job/<jobpk>/jobrel/<pk>/list/` page (Why do we need AJAX? Because candidate list is going to be a large list and we cannot reload the whole list on every update action on that page.)
- [ ] Downloading CV in bulk. We need to think of some mechanism to prepare a zip of all CVs before the recruiters asks for it.
- [x] Mechanism for downloading all **Jobs** as CSV on administrator side (Information on required fields is needed. Do we need to download programmes as well?)
- [x] Mechanism for downloading all **Companies** as CSV on administrator side (Information on required fields is needed.)
- [x] Mechanism for downloading selective  **Student** data (based on some parameters et to be decided) as CSV on administrator side (Which fields are required? Do we need any check-box type selection of fields to be downloaded?)
## Security TODO
- [ ] How to tackle brute force? IITG-WiFi probably gives same IP (202.141.80.24) for all users accessing portal through WiFi. 
- [ ] After login username can be used for throttling/rate-limiting, but what if an unauthenticated user is brute-forcing the login page. Use IP-based throttling? But if attacker is using IITG-WiFi then all users accessing portal through WiFi will suffer.
